/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_C34BE531__
#define __PLUGINEDITOR_H_C34BE531__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class ChaosChimpAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    ChaosChimpAudioProcessorEditor (ChaosChimpAudioProcessor* ownerFilter);
    ~ChaosChimpAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_C34BE531__
